# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates iproute systemd systemd-sysv python-pip && \
    apt-get clean

# https://github.com/moby/moby/issues/28614#issuecomment-310581026
STOPSIGNAL SIGRTMIN+3
RUN systemctl set-default multi-user.target
# TIP 2 solution 2
# RUN systemctl mask getty.target
#
# TIP 4
RUN mkdir -p /usr/share/man/man1