# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
{% if item.image == 'debian:bullseye-slim' %}
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y -q python3 sudo bash ca-certificates iproute2 systemd systemd-sysv python-lxml && \
    apt-get clean
{% else %}
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y -q python3 sudo bash ca-certificates iproute2 systemd systemd-sysv python3-lxml && \
    apt-get clean
{% endif %}

STOPSIGNAL SIGRTMIN+3
RUN systemctl set-default multi-user.target