---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: zookeeper
    hostname: zookeeper
    image: idealista/zookeeper:latest
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - zookeeper_group
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network

  - name: solrcloud1
    hostname: solrcloud1
    image: idealista/jdk:8u222-stretch-openjdk-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network
        aliases:
          - solrcloud1
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8983:8983/tcp

  - name: solrcloud2
    hostname: solrcloud2
    image: idealista/jdk:8u222-stretch-openjdk-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    groups:
      - solrcloud
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: solr-network
        aliases:
          - solrcloud2
        links:
          - zookeeper:zookeeper
    published_ports:
      - 0.0.0.0:8984:8983/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
  directory: ./tests
