# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates \
 systemd build-essential libffi-dev libssl-dev python-pip python-dev python-setuptools python-wheel net-tools \
    && apt-get clean; fi
